version: '3'
services: 
  react-client:
    build:
      context: ./client
    container_name: react-front
    volumes:
    - ./client/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "9000:80"
  api-server:
    build:
      context: ./server
    container_name: nodejs-server
    hostname: backend-node
    env_file:
    - ./server/.env
    depends_on:
    - mysql-db    
  mysql-db:
    image: mysql:8.0.28
    container_name: nodejs-db
    environment: 
      MYSQL_ROOT_PASSWORD: Zaq12wsx
    volumes: 
    - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    